name: paperplanes
favicon: null
layout_spectrum: 0.65883
typography_spectrum: 0.43338
title: 'Paper Planes - A strategic, content first agency'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53996341-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d3d3d3'
    - '#ee5c1e'
    - '#7b7b7b'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
